# Generated by Django 4.2.2 on 2023-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0032_user_password_forget_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='after_discount',
            field=models.IntegerField(verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Final Price'),
        ),
    ]
