# Generated by Django 4.2.2 on 2023-12-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_is_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_returned',
            new_name='is_cancel',
        ),
    ]
